name: CMake Build Matrix
on: [push]
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows MSVC", artifact: "Windows-MSVC.tar.xz",
            os: windows-latest,
            build_type: "Release", cc: "cl", cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }
#        - {
#            name: "Ubuntu Clang", artifact: "Linux.tar.xz",
#            os: ubuntu-latest,
#            build_type: "Release", cc: "clang", cxx: "clang++"
#          }

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{ github.workspace }}/build

    - name: Configure CMake
      shell: cmake -P {0}
      working-directory: ${{ github.workspace }}/build
      run: |
        set(ENV{CC} ${{ matrix.config.cc }})
        set(ENV{CXX} ${{ matrix.config.cxx }})
        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE
